### ISSUE TITLE
Add Powered by Apideck to backdrop

### ISSUE THREAD

**Issue by Gdewilde** [apideck-libraries/file-picker#1]
<img width="554" alt="Screenshot 2021-09-23 at 15 23 21" src="https://user-images.githubusercontent.com/1112129/134515027-5d1cebce-aefa-439e-a80e-50b999fb7f59.png">

**Comment by jakeprins** [comment]
Should be live now at https://file-picker.apideck.dev/ 

Added a `showAttribution` prop to the component and updated the readme with a properties table. By default the attribution is visible. Also fixed a small issue when searching and added a link to the npm package on the demo page.
