### ISSUE TITLE
Add option to programmatically open the file picker

### ISSUE THREAD

**Issue by jakeprins** [apideck-libraries/file-picker#5]
Instead of relying on the trigger element, we should add an `open` and `onClose` prop so the file picker could also be opened programmatically.

**Comment by Gdewilde** [comment]
Any PR I need to review?

**Comment by jakeprins** [comment]
This was needed to auto-open the file-picker modal after coming back from Vault. You could test it at: https://file-picker.apideck.dev/. 

- Create a test session by clicking the button (it will set a query param in the return URL on the session)
- Open the dropdown and hit the "add integration" to go to vault
- Click the "return to application" on vault to go back to the file picker

The file picker should now open directly.

**Comment by Gdewilde** [comment]
👌
